# Generated by Django 4.2 on 2023-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='author_avatar',
            field=models.ImageField(upload_to='author-avatar/'),
        ),
    ]
